In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./tests/sample_inputs/sample_input_1.csv')
df

id  gender  race  decision  reward  state1  state2  state3
0   1       0     1         1       2       1       4       6
1   1       0     1         2       4       5       7       3
2   1       0     1         2       3       6       7       1
3   2       1     0         3       4       5       6       7
4   2       1     0         2       4       2       7       3
5   2       1     0         1       4       8      10       1
6   3       1     3         3       1       6       7       8
7   3       1     3         1       2       4       5       6
8   3       1     3         2       9       4       3       6

In [4]:
df['gender'].to_numpy()

array([0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [5]:
df[['state1', 'state2', 'state3']].to_numpy()

array([[ 1,  4,  6],
       [ 5,  7,  3],
       [ 6,  7,  1],
       [ 5,  6,  7],
       [ 2,  7,  3],
       [ 8, 10,  1],
       [ 6,  7,  8],
       [ 4,  5,  6],
       [ 4,  3,  6]], dtype=int64)

In [6]:
df[['state3', 'state1']]

state3  state1
0       6       1
1       3       5
2       1       6
3       7       5
4       3       2
5       1       8
6       8       6
7       6       4
8       6       4

In [8]:
df['state1']

0    1
1    5
2    6
3    5
4    2
5    8
6    6
7    4
8    4
Name: state1, dtype: int64

In [ ]:
df[['decision', 'reward']].to_numpy()[[1, 2, 4, 5, 7, 8], :]

array([[2, 4],
       [2, 3],
       [2, 4],
       [1, 4],
       [1, 2],
       [2, 9]], dtype=int64)